tags:
  - multisine

gradient_clip_val: 5

model:
  Class: ComplexNet
  description: Simple MLP based model that predicts via frequency domain. Time loss is now absolute error. With exponential magnitude output.
  future_work: Try lower learning rate, activation function, and more layers.
  params:
    c_channels: 7
    x_channels: 1
    out_channels: ${ model.params.x_channels }
    warmup_window: 64
    forecast_window: 64
    model: FakeComplexMLP
    use_polar_pre_split: false  # If true, the model will split the input into magnitude and phase before feeding it to the model. Make sure to use normal MSE then and an appropriate MLP model.
    mlp_hidden_dims: [2048, 1024, 1024, 512, 256,64]
    mlp_activation: SiLU
    output_activation: none
    train_rollout: ${ model.params.forecast_window }
    validation_rollout: ${ model.params.forecast_window }
    loss: FrequencyPhaseAmpMSE # L1Loss
    optimizer_params:
      lr: 0.001 # Default 0.001
      weight_decay: 0  # Default 0
      amsgrad: false  # Default false





data:
  Class: DummyDataSet # ShotWindowDataset or DummyDataSet
  n_frequencies: 10
  n_columns_C: 7
  n_columns_X: 1
  seq_length: 128
  random_start: true
  dir: ./data/
  file: 2024_05_01-NaNsFiltered.parquet
  time_last: true  # Sets the time dim as the last dim
  crop_margin: 1000  # Determines the unused period at start and end of each shot for preprocessing
  
  cols:
    meta:
    - ShotNum
    - time
    x: [
            # "FIR",  # density lijn Interferometer
            # "FIR_core",  # For the March dataset of 260 shots, the FIR_core signal is the same as FIR.
            # "PD",  # photodiode lijn op de divertor
            # "DML",  # Magnetische respons  correleert met de energie in het plasma
            "POHM",  # Gemeten power waarde meet de power die uit wrijving komt
            # "Z_axis",  # center Plasma positie in de verticale lijn. deviation van reference is betekenis.
        ]
    c:
    - IP  # Current (niet reference lijn voor controller, maar de ware input. Dan laat je control bij control)
    - gas_fringes  # Ingepompte gas
    - NBI  # manieren om te verhitten: colliding Neutral beam injection
    - ECRH  # magnetron.
    - a_minor  # The radius of the smallest cross-section of the plasma, related to plasma shape and confinement efficiency.
    - KAPPA # Describes the ratio of plasma height to width, affecting stability and confinement.
    - DELTA  # linkerbovenhoek naar links vanuit hetmidden
    # # From X:
    # -  "FIR_core"  # For the March dataset of 260 shots, the FIR_core signal is the same as FIR.
    # - "DML"
    # - "POHM"
    # - "Z_axis"

    label:
    - LHD_label
