epochs: 6000
batch_size: 128
patience: 1000
gradient_clip_val: 1000
preview_data: true

# model: model.yaml # To be replaced by respective yaml file content
model: 
  Class: FlowModule
  params:
    model: VelocityNet
    model_params:
      input_dim: 2
      h_dim: 64
    loss: MSELoss
    optimizer_params:
      lr: 0.001
      weight_decay: 0  # Default 0
      amsgrad: false  # Default false
    
data:
  Class: SourceTargetDS
  source_distribution: gaussian
  target_distribution: heart
  n: 1000
