epochs: 6000
batch_size: 64
patience: 400
gradient_clip_val: 1
preview_data: false
plot_functions:
  # - key: spectogram_plot
  #   n: 5
  - key: 2d_flow_plot
    n: 64
  - key: line_flow_plot
    n: 5
  - key: multi_channel_lines
    n: 5


# model: model.yaml # To be replaced by respective yaml file content
# hidden_features: int = 128,
#         activation: nn.Module = nn.GELU(),
#         norm: bool = False,
#         ch_mults=(2, 2, 2, 2),
#         is_attn=(False, False, False, False),
#         mid_attn: bool = False,
#         n_blocks: int = 2,
#         use1x1: bool = False,
model: 
  Class: FlowModule
  params:
    prior: 'normal'  # normal, copy
    ot_method: 'exact'  # null to disable
    ot_replace: false  # Default false
    model: ConditionalUNet  # Must accept x, t inputs
    model_params:
      conditioning: ['x_history'] # will affect architecture
      spatial_dim: 1
      input_channels: 5 # Default 3
      apex_hidden_channels: 64  # Default 128
      # activation: GELU  # Default GELU # TODO implement configurable activation
      time_embedding_channels: 128  # Default apex_hidden_channels * 4
      time_embedding: sinusoidal  # default: sinusoidal, other: dummy
      ch_mults: [2, 2, 2, 2]  # Default [1, 2, 2, 4]
      is_attn: [false, false, false, false] # Default [false, false, false, false]
      mid_attn: false # Default false
      n_blocks: 2 # Default 2. Number of residual blocks
      norm_groups: 0 # Default false
      use1x1: false # Default false
    loss: MSELoss
    optimizer_params:
      lr: 0.001
      weight_decay: 0  # Default 0
      amsgrad: false  # Default false
    
data:
  Class: ShotFlowDS
  dir: ./data/
  file: 2024_05_01-NaNsFiltered.parquet
  seq_length: 500
  history_length: ${ data.seq_length } # default null / 0, if positive int, will include x_history in the conditioning_inputs
  crop_margin: 2000  # Determines the unused period at start and end of each shot for preprocessing
  force_start: 11000
  random_start: false
  force_fixed_shot: null # int if you want to overfit on one data point or null
  force_mean_zero: true
  time_last: true  # Sets the time dim as the last dim
  sample_rate: 10000
  cols:
    meta:
    - ShotNum
    - time
    x: [
            # "FIR",  # density lijn Interferometer (not in my dataset)
            "FIR_core",  # For the March dataset of 260 shots, the FIR_core signal is the same as FIR.
            "PD",  # photodiode lijn op de divertor
            "DML",  # Magnetische respons  correleert met de energie in het plasma
            "POHM",  # Gemeten power waarde meet de power die uit wrijving komt
            "Z_axis",  # center Plasma positie in de verticale lijn. deviation van reference is betekenis.
        ]
