# This will be merged into the inherited config from the base run

base_run: seq_levy_smC_BIG # ID or unique name
prefer_model_alias: best # null just takes the one with latest, can be best or latest.

test_cache_name: R_seq_levy_smC_BIG #test_tinyhistory # test_cache_unflow #  # tinyhistory_seq_normal_smC_BIG #${ run_name }
test_cache_mode: use # create or use

batch_size: 256
data:
  batch_size: 256

evaluation:
  n_steps: 40 # enough for rk4
  solve_method: rk4 # dopri5, euler, midpoint
  plot_functions:
  # every item has to have a 'key' key.
  # n are optional through defaults in PlotsCallback
  # all other keys are passed as kwargs to the plot function
  # - key: 2d_flow_plot
  # #   n: 64
  - key: animated_traces
    n: 5
  - key: multi_channel_lines
    n: 16
    buttons: true
  # Prominence histograms
  # - key: histogram  # see histograms.py
  #   log_key: peak_histogram/dml_energy_delta
  #   channel_name: DML
  #   measure: energy_delta
  #   n: 64



window_set:
  - [57013, 0.94]
  - [57013, 1.08]
  - [73368, 0.38] # All low and boring
  - [77604, 0.72]
  - [77604, 0.77]
  - [77409,1.32]
  - [73631, 1.03]
  - [69514, 0.51]
  - [69514, 0.51]
  - [64770, 0.17] # L Mode boringness
  - [64770, 1.09] # H Mode boringness, middenhoog NBI
  - [61028, 0.98] # 75%
  - [61028, 1.12] # 78%
  - [77595, 0.94] # High NBI
  - [76702, 1.14] # high NBI