# This will be merged into the inherited config from the base run

base_run: seq_normal_smC_BIG4 # ID or unique name
prefer_model_alias: best # null just takes the one with latest, can be best or latest.

test_cache_name: seq_normal_smC_BIG4_reeval_rk440 #${ run_name }
test_cache_mode: use # create or use

batch_size: 256
data:
  batch_size: 256

evaluation:
  n_steps: 40 # enough for rk4
  solve_method: rk4 # dopri5, euler, midpoint
  plot_functions:
  # every item has to have a 'key' key.
  # n are optional through defaults in PlotsCallback
  # all other keys are passed as kwargs to the plot function
  # - key: 2d_flow_plot
  # #   n: 64
  - key: animated_traces
    n: 5
  - key: multi_channel_lines
    n: 16
    buttons: true
  # Prominence histograms
  # - key: histogram  # see histograms.py
  #   log_key: peak_histogram/dml_energy_delta
  #   channel_name: DML
  #   measure: energy_delta
  #   n: 64


window_set:
  - [57013, 1.08]
  - [77604, 0.77]
  - [73631, 1.03]
  - [69514, 0.51]
  - [69514, 0.51]
