program: run.py
name: PosEncodings
method: random
metric:
  goal: minimize
  name: loss/val
parameters:
  model.params.optimizer_params.lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0001
  batch_size:
    values: [64, 96, 128]
  data.seq_length:
    values: [128, 256]
  data.crop_margin:
    values: [1000, 8000]
  data.cols.x:
    values: 
      - [ "FIR_core", "PD", "DML", "POHM", "Z_axis"]
      - ["PD", "DML"]
      - ["POHM", "Z_axis"]
  model.params.model_params.conditioning_method:
    values: ['sequence', 'channels']
  model.params.model_params.mid_attn:
    values: [true, false]
  model.params.model_params.is_attn:
    values: [[true, true, true, true], [false, false, false, false],  [true, false, false, false], [true, true, false, false]]
  model.params.model_params.apex_hidden_channels:
    values: [64, 128]
  model.params.model_params.attn_heads:
    values: [1, 2, 4]
  model.params.model_params.norm_groups:
    values: [1, 4]
  model.params.batch_rematch_factor:
    values: [32, 64]
  model.params.model_params.time_embedding:
    values: ['sinusoidal', 'sinusoidal', 'sinusoidal', 'sinusoidal+mlp', 'sinusoidal+mlp', 'dummy']
  model.params.model_params.time_embedding_d:
    values: [8, 32, 64]
  model.params.model_params.positional_encoding:
    values: ['sinusoidal', 'sinusoidal', 'sinusoidal', 'sinusoidal+mlp','sinusoidal+mlp', 'dummy']
  model.params.model_params.positional_encoding_d:
    values: [8, 32, 64]
  model.params.model_params.positional_encoding_c:
    values: [4, 16, 64, 128]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

## Start with `wandb sweep configs/sweep.yaml -p flowtoy`