program: run.py
name: BigConditioningSweep
method: random
metric:
  goal: minimize
  name: loss/val
parameters:
  model.params.optimizer_params.lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0001
  batch_size:
    values: [64, 96, 128]
  data.seq_length:
    values: [128, 256, 512, 1024]
  data.crop_margin:
    values: [1000, 2000, 4000, 8000]
  data.cols.x:
    values: 
      - [ "FIR_core", "PD", "DML", "POHM", "Z_axis"]
      - ["PD", "DML"]
      - ["POHM", "Z_axis"]
  model.params.model_params.conditioning_method:
    values: ['sequence', 'channels']
  model.params.model_params.mid_attn:
    values: [true, false]
  model.params.model_params.is_attn:
    values: [[true, true, true, true], [false, false, false, false],  [true, false, false, false], [true, true, false, false]]
  model.params.model_params.attn_heads:
    values: [1, 2, 4]
  model.params.model_params.norm_groups:
    values: [0, 1, 4, 8]
  model.params.batch_rematch_factor:
    values: [1, 12, 32]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

## Start with `wandb sweep configs/sweep.yaml -p flowtoy`